#!/bin/sh

bat=/sys/class/power_supply/BAT0
if [ ! -e "$bat" ]; then
  bat=/sys/class/power_supply/BAT1
fi
[ -e "$bat" ] && per="$(cat "$bat/capacity")"

icon() {
  [ ! -e "$bat" ] && exit
  [ $(cat "$bat/status") = Charging ] && echo "󱐋" && exit

  if [ "$per" -gt "90" ]; then
    icon="󱟢"
  elif [ "$per" -gt "80" ]; then
    icon="󰂂"
  elif [ "$per" -gt "70" ]; then
    icon="󰂁"
  elif [ "$per" -gt "60" ]; then
    icon="󰂀"
  elif [ "$per" -gt "50" ]; then
    icon="󰁿"
  elif [ "$per" -gt "40" ]; then
    icon="󰁾"
  elif [ "$per" -gt "30" ]; then
    icon="󰁽"
  elif [ "$per" -gt "20" ]; then
    icon="󰁼"
  elif [ "$per" -gt "10" ]; then
    icon="󰁻"
  elif [ "$per" -gt "0" ]; then
    icon="󰂃"
  else
    echo "󱟢" && exit
  fi

  echo "$icon"
}

percent() {
  echo $per
}

class() {
  [ ! -e "$bat" ] && exit
  [ $(cat "$bat/status") = Charging ] && echo "charging" && exit

  if [ "$per" -gt "60" ]; then
    class="great"
  elif [ "$per" -gt "40" ]; then
    class="medium"
  elif [ "$per" -gt "20" ]; then
    class="charge"
  elif [ "$per" -gt "0" ]; then
    class="critical"
  else
    echo "unknown" && exit
  fi

  echo "$class"
}

is_visible() {
  if [ -e "$bat" ]; then
    printf "true"
    return 0
  fi

  printf "false"
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
[ "$1" = "class" ] && class && exit
[ "$1" = "is_visible" ] && is_visible && exit
