#!/bin/sh

bat=/sys/class/power_supply/BAT1/
per="$(cat "$bat/capacity")"

image() {

# [ $(cat "$bat/status") = Charging ] && echo "" && exit

if [ "$per" -gt "90" ]; then
  heart="~/.config/bspwm/bar/images/icons/battery/100.png"
elif [ "$per" -gt "80" ]; then
  heart="~/.config/bspwm/bar/images/icons/battery/80.png"
elif [ "$per" -gt "70" ]; then
  heart="~/.config/bspwm/bar/images/icons/battery/60.png"
elif [ "$per" -gt "60" ]; then
  heart="~/.config/bspwm/bar/images/icons/battery/60.png"
elif [ "$per" -gt "50" ]; then
  heart="~/.config/bspwm/bar/images/icons/battery/45.png"
elif [ "$per" -gt "40" ]; then
  heart="~/.config/bspwm/bar/images/icons/battery/45.png"
elif [ "$per" -gt "30" ]; then
  heart="~/.config/bspwm/bar/images/icons/battery/25.png"
elif [ "$per" -gt "20" ]; then
  heart="~/.config/bspwm/bar/images/icons/battery/25.png"
elif [ "$per" -gt "10" ]; then
  heart="~/.config/bspwm/bar/images/icons/battery/15.png"
	notify-send -u critical "Battery Low" "Connect Charger"
elif [ "$per" -gt "0" ]; then
  heart="~/.config/bspwm/bar/images/icons/battery/0.png"
	notify-send -u critical "Battery Low" "Connect Charger"
else
  heart="~/.config/bspwm/bar/images/icons/battery/0.png"
fi
echo "$heart"
}

icon() {

[ $(cat "$bat/status") = Charging ] && echo "" && exit

if [ "$per" -gt "90" ]; then
	icon=""
  heart="~/.config/bspwm/bar/images/icons/battery/100.png"
elif [ "$per" -gt "80" ]; then
	icon=""
  heart="~/.config/bspwm/bar/images/icons/battery/80.png"
elif [ "$per" -gt "70" ]; then
	icon=""
  heart="~/.config/bspwm/bar/images/icons/battery/60.png"
elif [ "$per" -gt "60" ]; then
	icon=""
  heart="~/.config/bspwm/bar/images/icons/battery/60.png"
elif [ "$per" -gt "50" ]; then
	icon=""
  heart="~/.config/bspwm/bar/images/icons/battery/45.png"
elif [ "$per" -gt "40" ]; then
	icon=""
  heart="~/.config/bspwm/bar/images/icons/battery/45.png"
elif [ "$per" -gt "30" ]; then
	icon=""
  heart="~/.config/bspwm/bar/images/icons/battery/25.png"
elif [ "$per" -gt "20" ]; then
	icon=""
  heart="~/.config/bspwm/bar/images/icons/battery/25.png"
elif [ "$per" -gt "10" ]; then
	icon=""
  heart="~/.config/bspwm/bar/images/icons/battery/15.png"
	notify-send -u critical "Battery Low" "Connect Charger"
elif [ "$per" -gt "0" ]; then
	icon=""
  heart="~/.config/bspwm/bar/images/icons/battery/0.png"
	notify-send -u critical "Battery Low" "Connect Charger"
else
        echo  && exit
fi
echo "$icon"
}

percent() {
echo $per
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
[ "$1" = "image" ] && image && exit
exit
