#!/bin/bash

history_eww_content() {
  notifications=$(dunstctl count history)
  if [ "$notifications" -eq "0" ]; then
   box=$(echo "(box 
    :orientation \"v\"
    :spacing 10 
    :space-evenly \"false\" 
    :class \"notification-container\"
    (label 
      :text \"No hay notificaciones\"))") 
   echo $box
   return
  fi

  notifications=$(dunstctl history | jq -r '.data[0][] |
    "(box 
      :orientation \"v\" 
      :class \"notification-box\" 
      :space-evenly \"false\" 
      :onrightclick \"dunstctl history-rm \(.id.data)\" 
        (label 
          :class \"appname\" 
          :halign \"start\" 
          :truncate \"true\" 
          :show-truncated \"true\" 
          :text \"\(.appname.data)\") 
        (label 
          :class \"summary\" 
          :halign \"start\" 
          :truncate \"true\" 
          :show-truncated \"true\" 
          :text \"\(.summary.data)\") 
        (label 
          :class \"body\" 
          :halign \"start\" 
          :truncate \"true\" 
          :show-truncated \"true\" 
          :text \"\(.body.data)\"))"')

  box=$(echo "(box 
    :orientation \"v\"
    :spacing 10 
    :space-evenly \"false\" 
    :class \"notification-container\"
      (button 
      :onclick \"dunstctl history-clear\" 
      :vexpand \"false\" 
      :class \"delete-notifications\" 
        (box
          (label 
            :wrap \"true\"
            :text \"borrar todo\"))) 
        $notifications)" | tr '\n' ' ') 

  echo $box
}

history_eww_content
dbus-monitor "interface='org.freedesktop.Notifications'" | while read -r _; do
  history_eww_content
done
