#!/bin/bash
# @requires: pactl
# @requires: pamixer

# SINK=$(pactl list short sinks | sed -e 's,^[0−9][0−9]∗[0−9][0−9]∗[^0-9].*,\1,' | head -n 1)
SINK="@DEFAULT_SINK@"

percentage() {
  local val=$(echo $1 | tr '%' ' ' | awk '{print $1}')
}

get_percentage() {
  local muted=$(pamixer --get-volume-human)
  if [[ $muted == 'muted' ]]; then
    echo 0%
  else
    echo $muted
  fi
}

get_icon() {
  local vol=$(get_percentage)
  if [[ $vol == "0%" ]]; then
    echo "images/icons/volume/mute.png"
  else
    echo "images/icons/volume/volume.png"
  fi
}

get_class() {
  local vol=$(get_percentage)
  if [[ $vol == "0%" ]]; then
    echo "muted"
  else
    echo "not-muted"
  fi
}

get_vol () {
  local percent=$(get_percentage)
  echo $percent | tr -d '%'
}

if [[ $1 == "--icon" ]]; then
  get_icon
fi

if [[ $1 == "--percentage" ]]; then
  get_percentage
fi

if [[ $1 == "--vol" ]]; then
  get_vol
fi

if [[ $1 == "--class" ]]; then
  get_class
fi

if [[ $1 == "--toggle-muted" ]]; then
  pamixer -t
fi

if [[ $1 == "set" ]]; then
  val=$(echo $2 | tr '.' ' ' | awk '{print $1}')
  if test $val -gt 100; then
    val=100
  fi
  pactl set-sink-volume $SINK $val%
fi
