#!/bin/sh

symbol() {
  if (curl -I archlinux.org || curl -I google.com) &> /dev/null; then
    echo " "
  else
    echo "󰤭"
  fi

}

color() {
  if (curl -I archlinux.org || curl -I google.com) &> /dev/null; then
    echo "#BB9AF7"
  else
    echo "#F7768E"
  fi
}

name() {
  nmcli | grep "^wlp" | sed 's/\ connected\ to\ /Connected to /g' | cut -d ':' -f2
}

[ "$1" = "name" ] && name && exit
[ "$1" = "color" ] && color && exit
[ "$1" = "icon" ] && symbol && exit
