#!/bin/sh

# Have to set this in order to work with every language
LANG=en_US

symbol() {
  if (curl -I archlinux.org || curl -I google.com) &> /dev/null; then
    echo " "
  else
    echo "󰤭"
  fi

}

class() {
  if (curl -I archlinux.org || curl -I google.com) &> /dev/null; then
    echo "conn-active"
  else
    echo "conn-inactive"
  fi
}

name() {
  nmcli | grep -E "^wl|^enps|^eth" | cut -d ':' -f2 | sed 's/connected to //'
}

[ "$1" = "name" ] && name && exit
[ "$1" = "class" ] && class && exit
[ "$1" = "icon" ] && symbol && exit
