#! /bin/sh
# rules

bspc rule -r "*"
bspc rule -a Brave-browser state=pseudo_tiled
bspc rule -a Alacritty state=pseudo_tiled

sh ~/.config/bspwm/scripts/RandomWall
picom &
eww daemon
sh ~/.config/bspwm/bar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config window_gap                    16

bspc config single_monocle                true
bspc config split_ratio                   0.5
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config center_pseudo_tiled			  true

bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child

bspc config remove_disabled_monitors      true 
bspc config merge_overlapping_monitors    true

bspc config border_width 2
bspc config focused_border_color "#dddff4"
bspc config normal_border_color "#0d0f18"

bspc config pointer_motion_interval       16
