#! /bin/sh
# autostart

sh $HOME/.config/bspwm/scripts/autostart

# rules
bspc rule -r "*"

bspc monitor -d 1 2 3 4 5 6 7

bspc config window_gap                    22

bspc config single_monocle                true
bspc config split_ratio                   0.5
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config center_pseudo_tiled			      true

bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner

bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child

bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

bspc config border_width                  2

bspc config normal_border_color         "#6d6e71"
bspc config active_border_color         "#d5a4b5"
bspc config focused_border_color        "#efe5dc"
bspc config presel_feedback_color       "#d5a4b5"
bspc config urgent_border_color         "#d5a4b5"

bspc config pointer_motion_interval       16
