#!/bin/bash

password=$(rofi -dmenu \
  -password \
  -i \
  -no-fixed-num-lines \
  -p "Password:" \
  -theme ~/.config/rofi/themes/askpass/askpass.rasi)

password=$(printf "%s" "$password" | tr -d '\n' | sed 's/[[:space:]]*$//')

printf "%s" "$password"
