#!/bin/sh

xsetroot -cursor_name left_ptr
feh --no-fehbg --bg-fill '/home/carlos/.config/bspwm/Wallpapers/bg.png'
picom &
eww daemon
sh ~/.config/bspwm/bar/launch.sh
export SUDO_ASKPASS=~/.config/bspwm/scripts/askpass
export PATH=$HOME/.bin:$PATH

pgrep -x sxhkd > /dev/null || sxhkd &

betterlockscreen -u '/home/carlos/.config/bspwm/Wallpapers/bg.png' & disown
