[general]
import = ["~/.config/alacritty/colors.toml"]

[font]
normal.family = "UbuntuMonoNerdFont"
bold.family = "UbuntuMonoNerdFont"
italic.family = "UbuntuMonoNerdFont"
bold_italic.family = "UbuntuMonoNerdFont"
size = 11.0

[window]
padding = {x = 10, y = 10}
